
<? echo View::content() ?>
<? echo Form::open("", "POST", "class='form-inline'") ?>

<div class='row'>

    <label>Buscar por</label>

    <? $arr = array("Semestre") ?>
    <? echo Form::Select("comboBusqueda", $arr, "class=''", "Semestre") ?>

   <?echo Form::dbSelect("tiposemestre_id",null,null,"Seleccione..","class='form-control'")?>

    <button type="submit" class="btn btn-purple btn-sm">
        <span class="ace-icon fa fa-search icon-on-right bigger-110"></span>
        Buscar
    </button>
    <? echo Html::link("movilidad/nuevo", "Crear nuevo", "class='btn btn-danger btn-sm'") ?>

</div>


<? echo Form::close(); ?>
<br>
<? View::partial('paginators/extended', false, array('page' => $arrMovilidad, 'url' => 'movilidad/index')); ?>
<br>
<table class='table table-striped'>
    <thead>
    <th>Nombres</th>
    <th>Ciudad</th>
    <th>País</th>    
    <th>Fecha</th>  
    <th>Tipo movilidad</th>  
    <th>Opciones</th>
</thead>

<? foreach ($arrMovilidad->items as $obj) { ?>

    <tr>
        <td><?
            $per = new Persona();
            $per->find_first($obj->persona_id);
            echo $per->nombrecompleto;
            ?></td>
        <td><? 
        
            $ciu = new Tipociudad();
            $ciu->find_first($obj->tipociudad_id);
                                
                    ?></td>

        <td>
            <?
            $tp = new Tipopais();
            $tp->find_first($ciu->tipopais_id);
            echo $tp->nombre;
            ?>
        </td>
        <td>
            <?echo $obj->fechamovilidad?>
        </td>
        <td>
            <?
                $tm = new Tipomovilidad();
                $tm->find_first($obj->tipomovilidad_id);
                echo $tm->nombre;
            
            ?>
        </td>
        <td>
            <div class="hidden-sm hidden-xs btn-group">
                <!--<button class="btn btn-xs btn-success">
                   
                    <i class="ace-icon fa fa-check bigger-120"></i>
                    
               </button>-->

                <div class="btn btn-xs btn-info">

                    <? echo Html::linkSoloIcono("ace-icon fa fa-pencil bigger-120", "", false, "movilidad/editar/$obj->id") ?>
                </div>

                <div class="btn btn-xs btn-danger">

                    <? echo Js::linkAction("eliminar/$obj->id", "", "¿Está seguro de eliminar?", "ace-icon fa fa-trash-o bigger-120") ?>
                </div>

                <!--<button class="btn btn-xs btn-warning">
                    <i class="ace-icon fa fa-flag bigger-120"></i>
                </button>-->
            </div>

            <div class="hidden-md hidden-lg">
                <div class="inline pos-rel">
                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                    </button>

                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                        <li>
                            <? echo "hola" ?>

                        </li>

                        <li>
                            <a href="#" class="tooltip-success" data-rel="tooltip" title="Edit">
                                <span class="green">
                                    <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete">
                                <span class="red">
                                    <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </td>
    </tr>

<? } ?>
</table>

<? View::partial('paginators/extended', false, array('page' => $arrMovilidad, 'url' => 'movilidad/index')); ?>