
<? echo View::content() ?>
<? echo Form::open("", "POST", "class='form-inline'") ?>

<div class='row'>

    <label>Buscar por</label>

    <? $arr = array("Titulo") ?>
    <? echo Form::Select("comboBusqueda", $arr, "class=''", "Titulo") ?>

   <? echo Form::text("busqueda", "placeholder='Escribe aquí..'", "") ?>

    <button type="submit" class="btn btn-purple btn-sm">
        <span class="ace-icon fa fa-search icon-on-right bigger-110"></span>
        Buscar
    </button>
    <? echo Html::link("investigacion/nuevo", "Crear nuevo", "class='btn btn-danger btn-sm'") ?>

</div>


<? echo Form::close(); ?>
<br>
<? View::partial('paginators/extended', false, array('page' => $arrInvestigacion, 'url' => 'investigacion/index')); ?>
<br>
<table class='table table-striped'>
    <thead>
    <th>Título</th>
    <th>Estado</th>
    <th>Fecha inicio</th>    
    <th>Fecha fin</th>
    <th>Semestre</th>     
    <th>Opciones</th>
</thead>

<? foreach ($arrInvestigacion->items as $obj) { ?>

    <tr>
        <td>
            <?echo $obj->titulo?>
        </td>
        <td><?
            $per = new Tipoestadoinvestigacion();
            $per->find_first($obj->tipoestadoinvestigacion_id);
            echo $per->nombre;
            ?>
        </td>
        <td><?echo $obj->fechainicio;?></td>
         <td><?echo $obj->fechafin;?></td>
            
        <td>
            <?
                $ts = new Tiposemestre();
                $ts->find_first($obj->tiposemestre_id);
                echo $ts->nombre;
            ?>
        </td>
       
        <td>
            <div class="hidden-sm hidden-xs btn-group">
                <!--<button class="btn btn-xs btn-success">
                   
                    <i class="ace-icon fa fa-check bigger-120"></i>
                    
               </button>-->

                <div class="btn btn-xs btn-info">

                    <? echo Html::linkSoloIcono("ace-icon fa fa-pencil bigger-120", "", false, "investigacion/editar/$obj->id") ?>
                </div>

                <div class="btn btn-xs btn-danger">

                    <? echo Js::linkAction("eliminar/$obj->id", "", "¿Está seguro de eliminar?", "ace-icon fa fa-trash-o bigger-120") ?>
                </div>
                
                <div class="btn btn-xs btn-group">

                    <? echo Html::linkSoloIcono("ace-icon fa fa-users bigger-120", "", false, "personavinculada/index/$obj->id") ?>
                </div>

                <!--<button class="btn btn-xs btn-warning">
                    <i class="ace-icon fa fa-flag bigger-120"></i>
                </button>-->
            </div>

            <div class="hidden-md hidden-lg">
                <div class="inline pos-rel">
                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                    </button>

                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                        <li>
                            <? echo "hola" ?>

                        </li>

                        <li>
                            <a href="#" class="tooltip-success" data-rel="tooltip" title="Edit">
                                <span class="green">
                                    <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete">
                                <span class="red">
                                    <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </td>
    </tr>

<? } ?>
</table>

<? View::partial('paginators/extended', false, array('page' => $arrInvestigacion, 'url' => 'investigacion/index')); ?>