
<? echo View::content() ?>
<?echo Form::open("institucionvinculada/index/$idinvestigacion")?>
<div class='row'>

    <label>Agregar</label>

    
   <?echo Form::dbSelect("tipoinstitucion_id","nombre",null,"Seleccione..","class='form-control'")?>

    <button type="submit" class="btn btn-purple btn-sm">
        <span class="ace-icon fa fa-search icon-on-right bigger-110"></span>
        Agregar
    </button>
    

</div>
<?echo Form::close()?>


<br>
<table class='table table-striped'>
    <thead>
    <th>Institución vinculada</th>
    <th>Opciones</th>
</thead>

<? foreach ($arrInstituciones as $obj) { ?>
    <?
        $per = new Tipoinstitucion();
        $per->find_first($obj->tipoinstitucion_id)
                
    ?>
    <tr>
        <td><?echo $per->nombre?></td>
       
      
        <td>
            <div class="hidden-sm hidden-xs btn-group">
                <!--<button class="btn btn-xs btn-success">
                   
                    <i class="ace-icon fa fa-check bigger-120"></i>
                    
               </button>-->

                <div class="btn btn-xs btn-danger">

                    <? echo Js::linkAction("eliminar/$idinvestigacion/$obj->id", "", "¿Está seguro de eliminar?", "ace-icon fa fa-trash-o bigger-120") ?>
                </div>

                <!--<button class="btn btn-xs btn-warning">
                    <i class="ace-icon fa fa-flag bigger-120"></i>
                </button>-->
            </div>

            <div class="hidden-md hidden-lg">
                <div class="inline pos-rel">
                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                    </button>

                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                        <li>
                            <? echo "hola" ?>

                        </li>

                        <li>
                            <a href="#" class="tooltip-success" data-rel="tooltip" title="Edit">
                                <span class="green">
                                    <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete">
                                <span class="red">
                                    <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </td>
    </tr>

<? } ?>
</table>

