
<? echo View::content() ?>
<? echo Form::open("","POST","class='form-inline'") ?>

<div class='row'>

    <label>Buscar por</label>

    <? $arr = array("Nivel") ?>
    <? echo Form::Select("comboBusqueda", $arr, "class=''", "Nivel") ?>

      <?echo Form::dbSelect("tiponivelingles_id",null,null,"Seleccione..","class='form-control'")?>
    
  
    <button type="submit" class="btn btn-purple btn-sm">
        <span class="ace-icon fa fa-search icon-on-right bigger-110"></span>
        Buscar
    </button>
    <? echo Html::link("idioma/nuevo", "Crear nuevo", "class='btn btn-danger btn-sm'") ?>

</div>


<? echo Form::close(); ?>
<br>
<? View::partial('paginators/extended', false, array('page' => $arrIdioma,'url' => 'idioma/index')); ?>
<br>
<table class='table table-striped'>
    <thead>
    <th>Id</th>
    <th>Persona</th>
    <th>Nivel de inglés</th>
    <th>Institución</th>
    <th>Fecha inicio</th>
    <th>Fecha fin</th>
    <th>Opciones</th>
</thead>

<? foreach ($arrIdioma->items as $obj) { ?>

    <tr>
        <td><? echo $obj->id ?></td>
        <td><? 
                $per = new Persona();
                $per->find_first($obj->persona_id);
                echo $per->nombrecompleto 
            ?>
       </td>
        <td><? 
        
                $tip = new Tiponivelingles();
                $tip->find_first($obj->tiponivelingles_id);
                echo $tip->nombre;
            ?>
        </td>
        <td>
            <?
            $tp = new Tipoinstitucion();
            $tp->find_first($obj->tipoinstitucion_id);
            echo $tp->nombre;
            ?>
        </td>
        <td>
           <?echo $obj->fechainicio?>
        </td>
          <td>
           <?echo $obj->fechafin?>
        </td>
        <td>
            <div class="hidden-sm hidden-xs btn-group">
                <!--<button class="btn btn-xs btn-success">
                   
                    <i class="ace-icon fa fa-check bigger-120"></i>
                    
               </button>-->

                <div class="btn btn-xs btn-info">
                   
                     <?echo Html::linkSoloIcono("ace-icon fa fa-pencil bigger-120","",false, "idioma/editar/$obj->id")?>
                </div>

                <div class="btn btn-xs btn-danger">
                    
                     <?echo Js::linkAction("eliminar/$obj->id","","¿Está seguro de eliminar?","ace-icon fa fa-trash-o bigger-120")?>
                </div>

                <!--<button class="btn btn-xs btn-warning">
                    <i class="ace-icon fa fa-flag bigger-120"></i>
                </button>-->
            </div>

            <div class="hidden-md hidden-lg">
                <div class="inline pos-rel">
                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                    </button>

                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                        <li>
                            <?echo "hola"?>
                            
                        </li>

                        <li>
                            <a href="#" class="tooltip-success" data-rel="tooltip" title="Edit">
                                <span class="green">
                                    <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="tooltip-error" data-rel="tooltip" title="Delete">
                                <span class="red">
                                    <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </td>
    </tr>

<? } ?>
</table>

<? View::partial('paginators/extended', false, array('page' => $arrIdioma,'url' => 'idioma/index')); ?>