<?echo View::content()?>
<?echo Form::openMultipart("institucion/nuevo", "role='form'")?>

<div class="form-group">
    <label>Nombre</label>
    <?echo Form::text("nombre","class='form-control'")?>
</div>
<div class="form-group">
    <label>Ciudad</label>
    <?echo Form::dbSelect("tipociudad_id",null,null,"Seleccione..","class='form-control'")?>
</div>

<div class="form-group">
    <?echo Form::submit("Guardar","class='btn btn-danger btn-sm'")?>
    <?echo Html::link("institucion/index","Cancelar")?>
</div>

<?echo Form::close()?>

<?echo View::content()?>